import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navLinks = [
    {
      displayName: "Home",
      url: "",
    },
    {
      displayName: "Committee",
      url: "committee",
    },
    {
      displayName: "Membership",
      url: "membership",
    },
    {
      displayName: "Events",
      url: "events",
    },
    {
      displayName: "Contact",
      url: "concact",
    },
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen w-full bg-[#0E0B0B] text-gray-200 antialiased">
          <div className="p-6">
            {/* Top Nav */}
            <nav className="relative mx-auto max-w-5xl py-3">
              {/* Toggle (hidden checkbox) */}
              <input
                id="menu-toggle"
                type="checkbox"
                className="menu-toggle"
                aria-label="Toggle menu"
              />

              {/* Bar: brand + hamburger */}
              <div className="md:hidden flex items-center justify-between px-2 md:px-0">
                <a
                  href="/"
                  className="text-lg font-semibold tracking-tight text-white"
                  aria-label="Home"
                >
                  AI Society
                </a>

                {/* Hamburger button (label controls the checkbox) */}
                <label
                  htmlFor="menu-toggle"
                  className="hamburger md:hidden"
                  aria-hidden="true"
                >
                  <span></span>
                  <span></span>
                  <span></span>
                </label>
              </div>

              {/* Desktop nav */}
              <div className="mt-2 hidden md:block">
                <div className="flex flex-wrap items-center justify-center gap-6 text-lg md:text-xl">
                  {navLinks.map((item) => (
                    <a
                      key={item.displayName}
                      href={`/${item.url}`}
                      className="group relative px-1 text-gray-300 transition-colors hover:text-white"
                    >
                      {item.displayName}
                      <span className="absolute -bottom-1 left-0 h-[2px] w-0 bg-gradient-to-r from-red-500 to-red-900 transition-all duration-300 group-hover:w-full"></span>
                    </a>
                  ))}
                </div>
              </div>

              {/* Mobile dropdown menu */}
              <div className="mobile-menu md:hidden">
                <div className="mobile-menu-inner">
                  {navLinks.map((item) => (
                    <a
                      key={item.displayName}
                      href={`/${item.url}`}
                      className="mobile-link"
                    >
                      {item.displayName}
                    </a>
                  ))}
                </div>
              </div>
            </nav>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
